#!/bin/bash

# Install dependencies
apt update
apt install -y git make build-essential liblzma-dev gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu

# Clone upstream
rm -rf upstream
mkdir -p upstream
git clone https://github.com/ipxe/ipxe.git upstream

# Checkout latest release
cd upstream
git checkout $(git describe --tags $(git rev-list --tags --max-count=1))

# Enable HTTPS
sed -i -e 's/#undef\tDOWNLOAD_PROTO_HTTPS/#define\tDOWNLOAD_PROTO_HTTPS/g' src/config/general.h

# Add the embedded script
cd src
cp ../../downstream/init.ipxe .

# Add the embedded script and use all cores
shopt -s expand_aliases
alias EMBEDDED_MAKE="make EMBED=\"init.ipxe\" -j$(nproc)"

# Build 32-bit X86
EMBEDDED_MAKE bin-i386-pcbios/ipxe.kpxe
EMBEDDED_MAKE bin-i386-efi/ipxe.efi

# Build 64-bit X86
EMBEDDED_MAKE bin-x86_64-efi/ipxe.efi

# Build 32-bit ARM
EMBEDDED_MAKE CROSS_COMPILE=arm-linux-gnueabi- ARCH=arm32 bin-arm32-efi/snp.efi

# Build 64-bit ARM
EMBEDDED_MAKE CROSS_COMPILE=aarch64-linux-gnu- ARCH=arm64 bin-arm64-efi/snp.efi

# Create tmp directory
rm -rf ../../tmp
mkdir -p ../../tmp

# Stage 32-bit X86
cp bin-i386-pcbios/ipxe.kpxe ../../tmp/ipxe-i386.kpxe
cp bin-i386-efi/ipxe.efi ../../tmp/ipxe-i386.efi

# Stage 64-bit X86
cp bin-x86_64-efi/ipxe.efi ../../tmp/ipxe-x86_64.efi

# Stage 32-bit ARM
cp bin-arm32-efi/snp.efi ../../tmp/ipxe-arm32.efi

# Stage 64-bit ARM
cp bin-arm64-efi/snp.efi ../../tmp/ipxe-arm64.efi

# Stage downstream files
cp ../../downstream/config.ipxe ../../tmp

# Create tar archive in staging directory
rm -rf ../../staging
mkdir -p ../../staging
tar -zcvf ../../staging/ipxe.tar.gz -C ../../tmp .

# Docker preperation stuff
# Create tmp directory
rm -rf ../../docker
mkdir -p ../../docker

# Stage 32-bit X86
cp bin-i386-pcbios/ipxe.kpxe ../../docker/ipxe-i386.kpxe
cp bin-i386-efi/ipxe.efi ../../docker/ipxe-i386.efi

# Stage 64-bit X86
cp bin-x86_64-efi/ipxe.efi ../../docker/ipxe-x86_64.efi

# Stage 32-bit ARM
cp bin-arm32-efi/snp.efi ../../docker/ipxe-arm32.efi

# Stage 64-bit ARM
cp bin-arm64-efi/snp.efi ../../docker/ipxe-arm64.efi

cp ../../downstream/config.ipxe ../../docker
